

require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'rake/testtask'

spec = Gem::Specification.new do |s|
  s.name = 'Rorth'
  s.version = '0.3'
  s.has_rdoc = true
  s.extra_rdoc_files = ['README.textile', 'LICENSE']
  s.summary = 'An interpreted, stack based language based on Forth.'
  s.description = s.summary
  s.author = 'Indigo Casson'
  s.email = 'atamiser@gmail.com'
  s.homepage = 'http://www.geeklob.wordpress.com'
  s.executables = ['rorth']
  s.files = %w(LICENSE README.textile Rakefile) + Dir.glob("{bin,lib,spec}/**/*")
  s.require_path = "lib"
  s.bindir = "bin"
end

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

Rake::RDocTask.new do |rdoc|
  files =['README.textile', 'LICENSE', 'lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  rdoc.main = "README.textile" # page to start on
  rdoc.title = "Rorth Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options << '--line-numbers'
end

Rake::TestTask.new do |t|
  t.test_files = FileList['test/**/*.rb']
end
